name: Crossfade Partners
favicon: null
layout_spectrum: 0.47592497197911143
typography_spectrum: 0.5102287894114852
title: crossfade partners - nyc
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#353b3f'
    - '#020204'
    - '#bb7f71'
    - '#7596ce'
    - '#e8ae9b'
  brandStrength: 0.1875
  lightness: 0.508402340579778
  saturation: 0.4804996498860419
  rhythmicContrast: 0.28811240661889315
purpose: []
